### ISSUE TITLE
As A Redis C Module?

### ISSUE THREAD

**Issue by jpe42** [tidwall/rocksdb-server#1]
Would it be possible to adapt something like this as a [Redis C Module](https://github.com/antirez/redis/blob/unstable/src/modules/INTRO.md)?

**Comment by tidwall** [comment]
I think it might be possible. Are you thinking of adding a RocksDB module?

**Comment by jpe42** [comment]
No, I've only written a more hello-worldish module ([redis-mutex](https://github.com/comodal/redis-locks/tree/master/redis/modules)).  I don't have the C knowledge to take something like this on. I just wanted to bring it up on the off chance you hadn't heard of the new Module feature.

**Comment by tidwall** [comment]
I worked on a GIS redis module back in June that adds a bunch of [Tile38](https://github.com/tidwall/tile38) commands. The module api is pretty cool stuff. I hope to have more time in the future to explore it further.

**Comment by tidwall** [comment]
Out of curiosity, does your redis-mutex module intend to be a replacement of the redlock pattern?

**Comment by jpe42** [comment]
It is the same idea, just another implementation of it.  I think the only difference is that it addresses the race condition issue when a failover takes place.
